markdown: kramdown
permalink: pretty
exclude: ['README.*', 'LICENSE.txt']
sass:
    style: expanded

# Main Headline, name required, subtitle optional
name: Dane Gauthier
subtitle: Frontend Developer

# Title attribute
title: Fuse Core

# Information for web crawlers / Google, all of them optional
# 'description' and 'keywords' simply set the corresponding meta tags,
# 'crawl' is the 'Robots' tag http://www.robotstxt.org/meta.html
robots:
    description: One line of text describing the content of the page in less than 140 characters.
    keywords: foo, bar, baz
    crawl: index,follow

# website address when deployed, also given as canonical link
url: https://tsjensen.github.io/fuse-core/

# The 'baseurl' is prepended to all website-internal links.
# 'baseurl' will often be '', but for a project page on gh-pages, it needs to be the project name.
# If not empty, be careful to keep the leading slash, and don't add a slash at the end.
baseurl: ''

# Enable Google Analytics. Leave empty (just "ga:" with subitems commented out) to disable.
# In order to comply with EU cookie law, enable 'cookieconsent' to show a little popup asking users to acknowledge the GA cookies.
# Also, some places require you to anonymize the users' IPs, which can be enabled via 'anonymizeip' below. You normally want that.
# https://support.google.com/analytics/answer/2763052
#ga:
ga:
    account: 'UA-120960520-1'
    cookieconsent: true
    anonymizeip: true

# A picture of you, square(!), at least 180x180 pixels, more is better. Recommended file size < 100 KB.
# Leave empty for generic placeholder image.
# You can use your GitHub image:
avatar: "images/profile.jpg"
#avatar:


# All the social media and other sites that we want to link to. The 'show' flag determines if the link is shown.
# The order of this list controls the order of the links on the page. Feel free to add.
links:
  - linkedin:
      name: LinkedIn
      show: true
      href: https://linkedin.com/in/YOUR_LINKEDIN_USERNAME/
      icon: fab fa-linkedin-in
  - github:
      name: GitHub
      show: true
      href: https://github.com/tsjensen
      icon: fab fa-github
  - blog:
      name: Blog
      show: true
      href: http://host.domain/your_blog
      icon: fas fa-book-open
  - email:
      name: Email
      show: true
      href: mailto:jonathan.doe@host.domain
      icon: fas fa-envelope
         # Extra HTML which will be displayed below the links. Keep it short. Leave empty to disable.
        # extra_html: www.google.com
      extra_html: >
            Any (multiline) text containing simple HTML,
            such as links or ... lorem ipsum.

#EOF
